% -*- latex -*-
\LoadClass[french]{beamer}

\RequirePackage[utf8]{inputenc}
\RequirePackage[T1]{fontenc}
\RequirePackage[upright]{fourier}

\usetheme{Dresden}
\usefonttheme{serif}
\usecolortheme{beaver}
\definecolor{darkred}{rgb}%
     {0.77254901960784320,
      0.07058823529411765,
      0.17647058823529413}

% \RequirePackage{siunitx}
% \sisetup{output-decimal-marker={,}}
% \RequirePackage{parskip}
% \RequirePackage[a4paper, margin=1in]{geometry}

\RequirePackage{tikz}
\RequirePackage{graphicx}

\RequirePackage{UTC101_maths}

\RequirePackage{array}
\RequirePackage{booktabs}

\RequirePackage{ragged2e}
\RequirePackage[autostyle]{csquotes}
\RequirePackage{babel}

\RequirePackage{hyperref}

\MakeOuterQuote{"}
\renewcommand*{\*}{\,}
\DeclareUnicodeCharacter{22C5}{\cdot}

\renewcommand*{\epsilon}{\varepsilon}

\newcounter{session}
\setcounter{session}{1}

\endinput
