% -*- latex -*-
\LoadClass[french, t]{beamer}

\RequirePackage[utf8]{inputenc}
\RequirePackage[T1]{fontenc}
\RequirePackage[upright]{fourier}

\usefonttheme{serif}

% \RequirePackage{siunitx}
% \sisetup{output-decimal-marker={,}}
% \RequirePackage{parskip}
% \RequirePackage[a4paper, margin=1in]{geometry}

\RequirePackage{UTC101_maths}

\RequirePackage{graphicx}

\RequirePackage{ragged2e}
\RequirePackage[autostyle]{csquotes}
\RequirePackage{babel}

\RequirePackage{hyperref}

\MakeOuterQuote{"}
\renewcommand*{\*}{\,}
\DeclareUnicodeCharacter{22C5}{\cdot}

\renewcommand*{\epsilon}{\varepsilon}

\newcounter{session}
\setcounter{session}{1}

\endinput
